recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import welcome
from .views import RecipeListView
from .views import RecipeDetailView
from .views import records

app_name = 'recipes'

urlpatterns = [
    path('', welcome, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', records, name='search'),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.FloatField(help_text='in minutes')
    difficulty = models.CharField(max_length=50, default='unknown')
    ingredients = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 10 and len(ingredients) < 7:
            difficulty = 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 7:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) <= 2:
            difficulty = 'Easy'  # Assign 'Easy' for cooking time 10 and ingredient count 2
        elif self.cooking_time >= 10 and len(ingredients) <= 7:
            difficulty = 'Intermediate'
        else:
            difficulty = 'Hard'
        return difficulty


    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=120)
    pic = models.ImageField(upload_to='users', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)

recipes/forms.py
from django import forms

CHART__CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFFIC__CHOICES = (
    ('#1', 'Easy'),
    ('#2', 'Intermediate'),
    ('#3', 'Hard'),
    
)


class RecipeSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFFIC__CHOICES)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('recipes:list')
        else:
            error_message = 'Something went wrong, Please try again'

    context = {
        'form': form,
        'error_message': error_message
    }

    return render(request, 'auth/login.html', context)


def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')


def media(request, file_path=None):
    from django.conf import settings as cfg
    media_root = getattr(cfg, 'MEDIA_ROOT', None)

    if not media_root:
        return HttpResponseBadRequest('Invalid Media Root Configuration')
    if not file_path:
        return HttpResponseBadRequest('Invalid File Path')

    with open(os.path.join(media_root, file_path), 'rb') as doc:
        response = HttpResponse(doc.read(), content_type='application/doc')
        response['Content-Disposition'] = 'filename=%s' % (file_path.split('/')[-1])
        return response

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeSearchForm
import pandas as pd
from .utils import get_chart, get_recipename_from_id
# Create your views here.


def welcome(request):
    return render(request, 'recipes/recipes_home.html')


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/list.html'


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'


def records(request):
    form = RecipeSearchForm(request.POST or None)
    recipe_df = None
    recipe_diff = None
    chart = None
    qs = None
    if request.method == 'POST':
        recipe_diff = request.POST.get('recipe_diff')
        chart_type = request.POST.get('chart_type')

        if recipe_diff == '#1':
            recipe_diff = 'Easy'
        if recipe_diff == '#2':
            recipe_diff = 'Medium'
        if recipe_diff == '#3':
            recipe_diff = 'Hard'

        qs = Recipe.objects.all()
        id_searched = []
        for obj in qs:
            diff = obj.calculate_difficulty()
            if diff == recipe_diff:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df,
                              labels=recipe_df['name'].values)

            recipe_df = recipe_df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipe_diff': recipe_diff,
        'chart': chart,
        'qs': qs,
    }

    return render(request, 'recipes/search.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

recipes/templates/recipes/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sweets&Treats | Details</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="{% static 'recipes/images/cupcake-favicon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/cookbook3.jpg' %}") no-repeat fixed;
            background-size: cover;
        }

        .nav-bar {
            display: flex;
            justify-content: flex-end;
        }

        .logout_btn {
            margin-right: 20px;
            margin-left: 10px;
            border-radius: 5px;
            color: #000;
        }

        .details_long {
            margin-top: -90px;
            display: flex;
            justify-content: flex-start;
        }

        </style>
</head>

<body>
    <div class="nav-bar">
        <a href="{%url 'recipes:search' %}" class="logout_btn"> Search</a>
        <a href="{%url 'logout' %}" class="logout_btn"> Logout</a>
    </div>
    <div class="details_modal">
        <h2>{{object.name}}</h2>
        <img class="food_image" src="{{object.pic.url}}" />
        <div class="details_body">
            <div class="details_short">
                <b>Name: </b> {{object.name}} <br />
                <b>Cooking Time: </b> {{object.cooking_time}} <br />
                <b>Difficulty: </b> {{object.calculate_difficulty}} <br />
                <b>Ingredients: </b> {{object.ingredients}} <br /><br />
            </div>
        </div>
        <div class="details_long">
            <button onclick="goBack()" class="login_btn">Back</button>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
</body>

</html>

recipes/templates/recipes/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sweets&Treats | Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="{% static 'recipes/images/cupcake-favicon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/cookbook3.jpg' %}") no-repeat fixed;
            background-size: cover;
        }

        .nav-bar {
            display: flex;
            justify-content: center;
            cursor: pointer;
        }

        .logout_btn {
            margin-right: 20px;
            margin-left: 10px;
            border-radius: 5px;
            color: #000;
            border-color: 2px #000;
        }

        .search_box {
            display: flex;
            align-items: center;
            margin-right: auto;
            position: relative;
        }

        .button-group {
            display: flex;
            align-items: center;
        }

        .logout-btn {
            margin-left: 10px;
            border-radius: 5px;
            color: #000;
            border: 2px solid #000;
        }

        .form-search-input {
            height: 34px;
            padding: 6px 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
        }

        .search_results {
            position: absolute;
            background-color: #fff;
            border: 1px solid #ddd;
            max-height: 200px;
            overflow-y: scroll;
            z-index: 1;
            width: 500px;
            top: 100%;
            left: 0;
        }

        .recipe_searched {
            padding: 5px;
            cursor: pointer;
        }

        .recipe_searched:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>

<body>
    <div class="nav-bar">
        <div class="search_box">
            <form action="" method="GET" class="form">
                {% csrf_token %}
                <input type="text" name="recipe_search" class="form_search_input" id="searchbar"
                    placeholder="Search:" onkeyup="search_recipe()" />
            </form>
            <br>

            <div class="search_results" autocomplete="off" style="display: none;">
                {% for object in object_list %}
                <p class="recipe_searched">
                    <a class="recipe_name"
                        style="font-size: 18px; font-variant: small-caps; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"
                        href="{{object.get_absolute_url}}"> {{object.name}} </a>
                </p>
                {% endfor %}
            </div>
        </div>
        <div class="button-group">
            <a href="{% url 'recipes:search' %}" class="logout_btn">Charts
            <a href="{% url 'logout' %}" class="logout_btn">Logout</a>
        </div>
    </div>

    <div>
        <header class="page-header">
            <img id="logo" src="{% static 'recipes/images/logo.png' %}" height="400px" width="450px" />
        </header>
    </div>
    <div class="recipe_grid">
        {% for object in object_list %}
        <div class="grid_item">
            <h4>
                <a class="recipe_name" href="{{object.get_absolute_url}}">
                    {{object.name}}
                </a>
            </h4>
            {% if object.pic %}
            <img class="food_image_grid" src="{{object.pic.url}}" />
        {% endif %}
        </div>
        {% endfor %}
    </div>
    <script src="{% static 'recipes/js/search.js' %}"></script>
</body>

</html>

recipes/templates/recipes/recipes_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sweets&Treats | Welcome</title>
    <meta name="viewport" content="'width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="{% static 'recipes/images/cupcake-favicon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/cookbook3.jpg' %}") no-repeat fixed;
            background-size: cover;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        img {
            border-radius: 15px;
            margin-top: 140px;
        }

        .nav-bar {
            display: flex;
            justify-content: flex-end;
        }

        .login_btn {
            margin-right: 20px;
            margin-left: 10px;
            border-radius: 5px;
            color: #000;
            margin-top: 20px;
            margin-bottom: 80px;
            height: 25px;
        }
    </style>
</head>

<body>
    <div class="nav-bar">
        <img class="navbar_img" src="{% static 'recipes/images/cupcake-favicon.png' %}" alt="Favicon">
        <a href="{% url 'login' %}" class="login_btn"> Login</a>
    </div>
    <div>
        <header class="page-header">
            <img src="{% static 'recipes/images/welcome.png' %}" />
        </header>
    </div>

</body>

</html>

recipes/templates/recipes/search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sweets&Treats | Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'recipes/images/cupcake-favicon.png' %}">
    <link rel='stylesheet' type='text/css' href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/cookbook3.jpg' %}") no-repeat fixed;
            background-size: cover;
            color: black;
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Roboto Mono', 'Calibri', 'Trebuchet MS', sans-serif;
            font-variant: small-caps;
        }

        .nav-bar {
            display: flex;
            justify-content: flex-end;
            cursor: pointer;
        }

        .form_data {
            background-color: rgba(255, 255, 255, 0.5);
            border-radius: 10px;
            padding: 20px;
            margin-top: 100px;
            color: #000;
            box-shadow: 5px 10px 15px #f7b4a7;
        }

        .logout_btn {
            margin-right: 20px;
        }

        h1 {
            font-size: 45px;
            text-align: center;
            margin-bottom: 10px;
        }

        table {
    background-color: white;
  }
    </style>
</head>

<body>
    <div class="nav-bar">
        <a href="{%url 'recipes:list' %}" class="logout_btn"> Recipes</a>
        <a href="{%url 'logout' %}" class="logout_btn"> Logout</a>

    </div>
<hr>
<form action="" method="POST" class="form_data">
    <h1>Search Recipes</h1>
    {% csrf_token %}
    {{form}}
    <button type="submit" class="login_btn">Search</button>

</form>
<br>
<br>
{% if recipe_df %}
{{recipe_df|safe}}
<br>
<img alt='chart' src="data:image/png;base64, {{chart|safe}}">
{% else %}
<h3> no data</h3>
{% endif %}
<br>
<button onclick="goBack()" class="login_btn">Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

</body>
</html>